from scraper_wowhead import buduj_mapping_01

# NAJPIERW PRZYGOTOWAC EXCEL W FOLDERZE 'SUROWE' --> 'wowhead_id_kraina_dodatek'
#    A. WEJSC W LINKI W PIERWSZEJ ZAKLADCE
#    B. SKOPIOWAC RECZNIE 3 KOLUMNY (JEST PRZYCISK NA TO NA STRONIE) DO POSZCZEGOLNCH TABEL
#    B. ODSWIEZYC TABELE W DRUGIM ARKUSZU (TAM JUZ DANE SA ZAGREGOWANE Z KILKU LINKOW)
# NASTEPNIE ODPALIC PONIZSZY SKRYPT.
# DANE SA 'DOPISYWANE' W BATCHACH POD OSTATNIM WIERSZEM I SKRYPT SPRAWDZA, CZY DANY LINK JUZ WYSTEPUJE (JAK TAK TO PRZECHODZI DALEJ)
buduj_mapping_01()