USE WoW_PL
;

CREATE TABLE dbo.NPC_STATUSY (
  TECH_ID BIGINT IDENTITY(1, 1) NOT NULL,
  NPC_ID_FK BIGINT NOT NULL,
  STATUS NVARCHAR(30) NOT NULL,
  NAZWA NVARCHAR(55) NOT NULL,
  DATA_STATUS DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_NPC_STATUSY PRIMARY KEY (TECH_ID),
  CONSTRAINT FK_NPC_STATUSY_NPC FOREIGN KEY (NPC_ID_FK) REFERENCES dbo.NPC(NPC_ID_MOJE_PK),
  CONSTRAINT CK_NPC_STATUSY_STATUS CHECK (STATUS IN (N'0_ORYGINA£', N'3_ZATWIERDZONO'))
)
;

CREATE INDEX IX_NPC_STATUSY
ON dbo.NPC_STATUSY (NPC_ID_FK, STATUS, DATA_STATUS DESC)
;

CREATE UNIQUE INDEX UX_NPC_STATUSY_ORYGINAL
ON dbo.NPC_STATUSY (NPC_ID_FK)
WHERE STATUS = N'0_ORYGINA£'
;