USE WoW_PL
;

CREATE TABLE dbo.DIALOGI_STATUSY (
  TECH_ID BIGINT IDENTITY(1, 1)      NOT NULL,
  MISJA_ID_MOJE_FK BIGINT            NOT NULL,

  SEGMENT NVARCHAR(30)               NOT NULL
    CHECK (SEGMENT IN (N'DYMEK', N'GOSSIP')),

  STATUS NVARCHAR(30)                NOT NULL
    CHECK (STATUS IN (N'0_ORYGINA£', N'1_PRZET£UMACZONO', N'2_ZREDAGOWANO', N'3_ZATWIERDZONO')),

  NR_BLOKU_DIALOGU INT               NOT NULL,
  NR_WYPOWIEDZI    INT               NOT NULL,
  NPC_ID_FK     BIGINT               NOT NULL,

  TRESC NVARCHAR(MAX)                    NULL,
  DATA_STATUS DATETIME2              NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_DIALOGI_STATUSY PRIMARY KEY (TECH_ID),

  CONSTRAINT FK_DIALOGI_STATUSY_MISJE
    FOREIGN KEY (MISJA_ID_MOJE_FK) REFERENCES dbo.MISJE(MISJA_ID_MOJE_PK),

  CONSTRAINT FK_DIALOGI_STATUSY_NPC
    FOREIGN KEY (NPC_ID_FK) REFERENCES dbo.NPC(NPC_ID_MOJE_PK)
    )
;

CREATE INDEX IX_DIALOGI_STATUSY
ON dbo.DIALOGI_STATUSY (MISJA_ID_MOJE_FK, SEGMENT, NR_BLOKU_DIALOGU, NR_WYPOWIEDZI, DATA_STATUS DESC)
;

CREATE UNIQUE INDEX UX_DIALOGI_STATUSY_ORYGINAL
ON dbo.DIALOGI_STATUSY (MISJA_ID_MOJE_FK, SEGMENT, NR_BLOKU_DIALOGU, NR_WYPOWIEDZI, NPC_ID_FK)
WHERE STATUS = N'0_ORYGINA£'
;
