USE WoW_PL
;
CREATE TABLE dbo.SLOWA_KLUCZOWE (
  SLOWO_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,
  
  SLOWO_EN NVARCHAR(100)         NOT NULL, 
  SLOWO_PL NVARCHAR(100)         NOT NULL,
  
  KATEGORIA NVARCHAR(50)             NULL,
  UWAGI_DLA_AI NVARCHAR(255)         NULL,

  DATA_DODANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_SLOWA_KLUCZOWE PRIMARY KEY (SLOWO_ID_PK),
  CONSTRAINT UX_SLOWA_KLUCZOWE UNIQUE (SLOWO_EN, KATEGORIA) 
)
;