WITH ile_razy_wystepuje AS (
    SELECT
        MISJA_ID_MOJE_PK,
        MISJA_ID_Z_GRY,
        MISJA_URL_WIKI,
        COUNT(MISJA_ID_Z_GRY) OVER (PARTITION BY MISJA_ID_Z_GRY) AS CNT
    FROM dbo.MISJE
    WHERE MISJA_ID_Z_GRY != 123456789
),

cnt_i_dlugosc AS (
    SELECT
        MISJA_ID_MOJE_PK,
        MISJA_ID_Z_GRY,
        MISJA_URL_WIKI,
        CNT,
        LEN(MISJA_URL_WIKI) AS DLUGOSC_URL,
        MIN(LEN(MISJA_URL_WIKI)) OVER (PARTITION BY MISJA_ID_Z_GRY) AS MIN_DLUGOSC
    FROM ile_razy_wystepuje
    WHERE CNT > 1
)

SELECT
    MISJA_ID_MOJE_PK,
    CASE
        WHEN CNT = 2 AND DLUGOSC_URL = MIN_DLUGOSC THEN '123456789'
        WHEN CNT = 2 THEN MISJA_ID_Z_GRY
        WHEN CNT >= 3 AND DLUGOSC_URL = MIN_DLUGOSC THEN MISJA_ID_Z_GRY
        WHEN CNT >= 3 THEN '123456789'
        ELSE MISJA_ID_Z_GRY
    END AS MISJA_ID_Z_GRY
FROM cnt_i_dlugosc