SELECT m.MISJA_ID_MOJE_PK
FROM dbo.MISJE AS m
WHERE m.KRAINA_EN = 'Exile''s Reach'
  AND m.MISJA_ID_Z_GRY IS NOT NULL
  AND m.MISJA_ID_Z_GRY <> 123456789
  AND NOT EXISTS (
    SELECT 1
    FROM dbo.MISJE_STATUSY AS ms
    WHERE ms.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
      AND ms.STATUS = N'1_PRZET£UMACZONO'
  )
;