WITH Statusy_Agg AS (
    SELECT 
        MISJA_ID_MOJE_FK,
        STRING_AGG(ISNULL(TRESC, ''), '. ') AS TRESC_STATUSOW
    FROM dbo.MISJE_STATUSY
    WHERE STATUS = '0_ORYGINA£'
    GROUP BY MISJA_ID_MOJE_FK
),
Dialogi_Agg AS (
    SELECT 
        MISJA_ID_MOJE_FK,
        STRING_AGG(ISNULL(TRESC, ''), '. ') AS TRESC_DIALOGOW
    FROM dbo.DIALOGI_STATUSY
    WHERE STATUS = '0_ORYGINA£'
    GROUP BY MISJA_ID_MOJE_FK
)
SELECT 
    m.MISJA_ID_MOJE_PK,
    m.MISJA_TYTUL_EN + '. ' + 
    COALESCE(s.TRESC_STATUSOW, '') + '. ' + 
    COALESCE(d.TRESC_DIALOGOW, '') AS PELNY_TEKST
FROM dbo.MISJE AS m
LEFT JOIN Statusy_Agg AS s 
    ON m.MISJA_ID_MOJE_PK = s.MISJA_ID_MOJE_FK
LEFT JOIN Dialogi_Agg AS d 
    ON m.MISJA_ID_MOJE_PK = d.MISJA_ID_MOJE_FK
WHERE m.DODATEK_EN = 'Midnight'
  AND m.MISJA_ID_MOJE_PK = 1;