DELETE FROM dbo.DIALOGI_STATUSY
WHERE MISJA_ID_MOJE_FK = 150;

DELETE FROM dbo.MISJE_STATUSY
WHERE MISJA_ID_MOJE_FK = 150;

DELETE FROM dbo.ZRODLO
WHERE MISJA_ID_MOJE_FK = 150;

DELETE FROM dbo.MISJE
WHERE MISJA_ID_MOJE_PK = 150;