SELECT 'MISJE', *
FROM dbo.MISJE
WHERE 1=1
  AND MISJA_TYTUL_EN = 'Warming Up'
  AND MISJA_ID_Z_GRY != 123456789
  AND DODATEK_EN = 'Midnight'
  AND MISJA_ID_MOJE_PK IN (129, 130, 131)
  --AND KRAINA_EN = 'Exile''s Reach'
  --AND MISJA_URL_WIKI = 'https://warcraft.wiki.gg/wiki/A_Hunter%27s_Trap_(Horde)'
  --AND MISJA_TYTUL_EN = 'The Divine''s Shield'
  AND NPC_KONIEC_ID = 658
;

SELECT 'MISJE_STATUSY', ms.*
FROM dbo.MISJE_STATUSY AS ms
INNER JOIN dbo.MISJE AS m
  ON ms.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  AND m.MISJA_ID_MOJE_PK = 146
  --AND m.KRAINA_EN = 'Exile''s Reach'
;

SELECT 'NPC', *
FROM dbo.NPC
ORDER BY NAZWA DESC
;

SELECT 'NPC_STATUSY', *
FROM dbo.NPC_STATUSY
WHERE NPC_ID_FK = 2
;

SELECT 'DIALOGI_STATUSY', ds.*
FROM dbo.DIALOGI_STATUSY AS ds
INNER JOIN dbo.MISJE AS m
  ON ds.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  --AND m.KRAINA_EN = 'Exile''s Reach'
  AND m.MISJA_ID_MOJE_PK = 5
;

SELECT 'ZRODLO', *
FROM dbo.ZRODLO
WHERE MISJA_ID_MOJE_FK = 1
;

SELECT 'URLE', *
FROM dbo.LINKI_DO_SCRAPOWANIA
;

SELECT 'SLOWA_KLUCZOWE', *
FROM dbo.SLOWA_KLUCZOWE
;

SELECT 'MISJE_SLOWA_KLUCZOWE', *
FROM dbo.MISJE_SLOWA_KLUCZOWE
;