SELECT 'MISJE', *
FROM dbo.MISJE
WHERE 1=1
  --AND MISJA_ID_MOJE_PK = 911
  AND KRAINA_EN = 'Exile''s Reach'
;

SELECT 'MISJE_STATUSY', ms.*
FROM dbo.MISJE_STATUSY AS ms
INNER JOIN dbo.MISJE AS m
  ON ms.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  AND m.KRAINA_EN = 'Exile''s Reach'
;

SELECT 'NPC', *
FROM dbo.NPC
;

SELECT 'NPC_STATUSY', *
FROM dbo.NPC_STATUSY
WHERE NPC_ID_FK = 127
;

SELECT 'DIALOGI_STATUSY', *
FROM dbo.DIALOGI_STATUSY
;

SELECT 'ZRODLO', *
FROM dbo.ZRODLO
;

SELECT 'URLE', *
FROM dbo.LINKI_DO_SCRAPOWANIA
;

SELECT 'SLOWA_KLUCZOWE', *
FROM dbo.SLOWA_KLUCZOWE
;

SELECT 'MISJE_SLOWA_KLUCZOWE', *
FROM dbo.MISJE_SLOWA_KLUCZOWE
;