SELECT 'MISJE', *
FROM dbo.MISJE
WHERE MISJA_ID_MOJE_PK = 273
;

SELECT 'MISJE_STATUSY', *
FROM dbo.MISJE_STATUSY;

SELECT 'NPC', *
FROM dbo.NPC;

SELECT 'NPC_STATUSY', *
FROM dbo.NPC_STATUSY
WHERE NPC_ID_FK = 127
;

SELECT 'DIALOGI_STATUSY', *
FROM dbo.DIALOGI_STATUSY;

SELECT 'ZRODLO', *
FROM dbo.ZRODLO;

SELECT 'URLE', *
FROM dbo.LINKI_DO_SCRAPOWANIA;

SELECT 'SLOWA_KLUCZOWE', *
FROM dbo.SLOWA_KLUCZOWE;

SELECT 'MISJE_SLOWA_KLUCZOWE', *
FROM dbo.MISJE_SLOWA_KLUCZOWE;