USE WoW_PL
;

CREATE TABLE dbo.MISJE_SLOWA_KLUCZOWE (
  MISJA_SLOWO_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,
  MISJA_ID_MOJE_FK  BIGINT                NOT NULL, 
  SLOWO_ID          BIGINT                NOT NULL,

  DATA_DODANIA      DATETIME2             NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_MISJE_SLOWA PRIMARY KEY (MISJA_SLOWO_ID_PK),  
  CONSTRAINT UX_MISJA_SLOWO UNIQUE (MISJA_ID_MOJE_FK, SLOWO_ID),   
  CONSTRAINT FK_MISJE_SLOWA_MISJA FOREIGN KEY (MISJA_ID_MOJE_FK) REFERENCES dbo.MISJE(MISJA_ID_MOJE_PK),
  CONSTRAINT FK_MISJE_SLOWA_SLOWO FOREIGN KEY (SLOWO_ID) REFERENCES dbo.SLOWA_KLUCZOWE(SLOWO_ID_PK)
)
;
