USE WoW_PL
;

CREATE TABLE dbo.NPC (
  NPC_ID_MOJE_PK BIGINT IDENTITY(1, 1) NOT NULL,
  NPC_ID_Z_GRY BIGINT                      NULL,

  NAZWA NVARCHAR(55) NOT NULL UNIQUE,
  PLEC  NVARCHAR(5)      NULL,
  RASA  NVARCHAR(55)     NULL,
  KLASA NVARCHAR(55)     NULL,
  TYTUL NVARCHAR(255)    NULL,

  ZRODLO_NAZWA NVARCHAR(20)            NOT NULL
    CHECK (ZRODLO_NAZWA IN (N'wiki', N'wowhead', N'wowdb', N'recznie', N'z addonu')),
  DATA_DODANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_NPC PRIMARY KEY (NPC_ID_MOJE_PK)
)
;
