USE WoW_PL
;

CREATE TABLE dbo.MISJE (
  MISJA_ID_MOJE_PK BIGINT IDENTITY(1, 1)  NOT NULL,
  MISJA_ID_Z_GRY BIGINT                   NULL,
  
  MISJA_URL_WIKI NVARCHAR(500)        NOT NULL,
  MISJA_URL_WOWHEAD NVARCHAR(500)         NULL,
  MISJA_TYTUL_EN NVARCHAR(500)        NOT NULL,
  KONTYNENT NVARCHAR(100)                 NULL,
  KRAINA    NVARCHAR(155)                 NULL,
  DODATEK   NVARCHAR(55)                  NULL,
  DODANO_W_PATCHU NVARCHAR(55)            NULL,


  MISJA_TYTUL_NASTEPNA_EN NVARCHAR(500)   NULL,
  MISJA_TYTUL_POPRZEDNIA_EN NVARCHAR(500) NULL,
  WYMAGANY_LVL INT                        NULL,
  NPC_START_ID BIGINT                     NULL,
  NPC_KONIEC_ID BIGINT                    NULL,
  DATA_DODANIA DATETIME2              NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_MISJE PRIMARY KEY (MISJA_ID_MOJE_PK),
  CONSTRAINT UX_MISJE_URL_WIKI UNIQUE (MISJA_URL_WIKI),

  CONSTRAINT FK_MISJE_NPC_START
    FOREIGN KEY (NPC_START_ID) REFERENCES dbo.NPC(NPC_ID_MOJE_PK),

  CONSTRAINT FK_MISJE_NPC_KONIEC
    FOREIGN KEY (NPC_KONIEC_ID) REFERENCES dbo.NPC(NPC_ID_MOJE_PK)
)
;