USE WoW_PL
;

CREATE TABLE dbo.LINKI_DO_SCRAPOWANIA (
  TECH_ID BIGINT IDENTITY(1, 1) NOT NULL,
  URL NVARCHAR(500)             NOT NULL,
  ZRODLO_NAZWA NVARCHAR(20)     NOT NULL
    CHECK (ZRODLO_NAZWA IN (N'wiki', N'wowhead', N'wowdb', N'recznie')),
  DATA_DODANIA DATETIME2        NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_LINKI_DO_SCRAPOWANIA PRIMARY KEY (TECH_ID),
  CONSTRAINT UX_LINKI_DO_SCRAPOWANIA_URL UNIQUE (URL)
)
;   

CREATE INDEX IX_LINKI_DO_SCRAPOWANIA_ZRODLO
ON dbo.LINKI_DO_SCRAPOWANIA (ZRODLO_NAZWA, DATA_DODANIA DESC)
;