SELECT 'MISJE', *
FROM dbo.MISJE
WHERE MISJA_ID_Z_GRY IS NULL

SELECT 'MISJE_STATUSY', *
FROM dbo.MISJE_STATUSY;

SELECT 'NPC', *
FROM dbo.NPC;

SELECT 'NPC_STATUSY', *
FROM dbo.NPC_STATUSY;

SELECT 'DIALOGI_STATUSY', *
FROM dbo.DIALOGI_STATUSY;

SELECT 'ZRODLO', *
FROM dbo.ZRODLO;

SELECT 'URLE', *
FROM dbo.LINKI_DO_SCRAPOWANIA;
