USE WoW_PL;
GO

CREATE TABLE dbo.MISJE (
  MISJA_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,
  ZRODLO_ID_FK BIGINT NOT NULL,
  TYTUL_EN NVARCHAR(255) NOT NULL,
  TYTUL_PL NVARCHAR(255) NULL,
  WYMAGANY_LVL INT NULL,
  NPC_START_ID BIGINT NULL,
  NPC_KONIEC_ID BIGINT NULL,
  DATA_DODANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  DATA_TLUMACZENIA DATETIME2 NULL,

  CONSTRAINT PK_MISJE PRIMARY KEY (MISJA_ID_PK),

  CONSTRAINT FK_MISJE_ZRODLO
    FOREIGN KEY (ZRODLO_ID_FK) REFERENCES dbo.ZRODLO(ZRODLO_ID_PK),

  CONSTRAINT FK_MISJE_NPC_START
    FOREIGN KEY (NPC_START_ID) REFERENCES dbo.NPC(NPC_ID_PK),

  CONSTRAINT FK_MISJE_NPC_KONIEC
    FOREIGN KEY (NPC_KONIEC_ID) REFERENCES dbo.NPC(NPC_ID_PK)
);
GO
