USE WoW_PL
GO

CREATE TABLE dbo.MISJE (
  MISJA_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,
  MISJA_URL NVARCHAR(500) NOT NULL,
  TYTUL_EN NVARCHAR(155) NOT NULL,
  WYMAGANY_LVL INT NULL,
  NPC_START_ID BIGINT NULL,
  NPC_KONIEC_ID BIGINT NULL,
  DATA_DODANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_MISJE PRIMARY KEY (MISJA_ID_PK),
  CONSTRAINT UX_MISJE_URL UNIQUE (MISJA_URL),

  CONSTRAINT FK_MISJE_NPC_START
    FOREIGN KEY (NPC_START_ID) REFERENCES dbo.NPC(NPC_ID_PK),

  CONSTRAINT FK_MISJE_NPC_KONIEC
    FOREIGN KEY (NPC_KONIEC_ID) REFERENCES dbo.NPC(NPC_ID_PK)
)
GO
