USE WoW_PL
GO

CREATE TABLE dbo.ZRODLO (
  ZRODLO_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,
  ZRODLO_NAZWA NVARCHAR(8) NOT NULL
	CHECK( ZRODLO_NAZWA IN ('wiki', 'wowhead', 'wowdb', 'recznie', 'z addonu') ),
  URL NVARCHAR(500) NOT NULL,
  DATA_WYSCRAPOWANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  HTML_HASH CHAR(64) NOT NULL,

  CONSTRAINT PK_ZRODLO PRIMARY KEY (ZRODLO_ID_PK),
  CONSTRAINT UX_ZRODLO_URL UNIQUE (URL)
)
GO
