USE WoW_PL
GO

CREATE TABLE dbo.NPC (
  NPC_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,

  NAZWA NVARCHAR(55) NOT NULL UNIQUE,
  PLEC NVARCHAR(5) NULL,
  RASA NVARCHAR(55) NULL,
  KLASA NVARCHAR(55) NULL,
  TYTUL NVARCHAR(255) NULL,

  DATA_DODANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_NPC PRIMARY KEY (NPC_ID_PK)
)
GO

SELECT *
FROM dbo.NPC;