USE WoW_PL
GO

CREATE TABLE dim.NPC (
  NPC_ID_PK INT IDENTITY PRIMARY KEY,
  NPC_NAZWA_EN NVARCHAR(255) NOT NULL UNIQUE,
  NPC_NAZWA_PL NVARCHAR(255) NULL,
  NPC_ID_PRAWDZIWE INT NULL, -- z API WoW/innego zrodla
  ZRODLO NVARCHAR(20) CHECK(Zrodlo IN ('wiki.gg', 'wowhead', 'wowdb', 'API WoW', 'z addonu', 'recznie')),
  KIEDY_DODANO DATETIME2 DEFAULT SYSDATETIME(),
  NOTATKI NVARCHAR(255) NULL
)
GO