USE WoW_PL
GO

CREATE TABLE dim.Quest (
  MISJA_ID_PK INT IDENTITY PRIMARY KEY,
  MISJA_URL NVARCHAR(255) UNIQUE NOT NULL,
  ZRODLO NVARCHAR(20) CHECK(Zrodlo IN ('wiki.gg', 'wowhead', 'wowdb', 'API WoW', 'z addonu', 'recznie')),
  KIEDY_DODANO DATETIME2 DEFAULT SYSDATETIME()
)
GO