USE WoW_PL
GO

CREATE TABLE dbo.NPC_STATUSY (
  TECH_ID BIGINT IDENTITY(1, 1) NOT NULL,
  NPC_ID_FK BIGINT NOT NULL,

  STATUS NVARCHAR(30) NOT NULL
    CHECK (STATUS IN (N'0_ORYGINA£', N'1_PRZET£UMACZONO', N'2_ZREDAGOWANO', N'3_ZATWIERDZONO')),

  NAZWA NVARCHAR(55) NULL,
  DATA_STATUS DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_NPC_STATUSY PRIMARY KEY (TECH_ID),
  CONSTRAINT FK_NPC_STATUSY_NPC FOREIGN KEY (NPC_ID_FK) REFERENCES dbo.NPC(NPC_ID_PK)
)
GO

CREATE INDEX IX_NPC_STATUSY
ON dbo.NPC_STATUSY (NPC_ID_FK, STATUS, DATA_STATUS DESC)
GO

CREATE UNIQUE INDEX UX_NPC_STATUSY_ORYGINAL
ON dbo.NPC_STATUSY (NPC_ID_FK)
WHERE STATUS = N'0_ORYGINA£'
GO