USE WoW_PL
GO

CREATE TABLE dbo.MISJE_STATUSY (
  TECH_ID BIGINT IDENTITY(1, 1) NOT NULL,
  MISJA_ID_FK BIGINT NOT NULL,

  SEGMENT NVARCHAR(30) NOT NULL
    CHECK (SEGMENT IN (N'CEL', N'TREŒÆ', N'POSTÊP', N'ZAKOÑCZENIE', N'NAGRODY')),
  PODSEGMENT NVARCHAR(30) NULL
    CHECK (PODSEGMENT IN (N'G£ÓWNY_CEL', N'PODRZÊDNY_CEL')),

  STATUS NVARCHAR(30) NOT NULL
    CHECK (STATUS IN (N'0_PRZET£UMACZONO', N'1_ZREDAGOWANO', N'2_ZATWIERDZONO')),

  TRESC_PL NVARCHAR(MAX) NULL,
  DATA_STATUS DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_MISJE_STATUSY PRIMARY KEY (TECH_ID),
  CONSTRAINT FK_MISJE_STATUSY_MISJE FOREIGN KEY (MISJA_ID_FK) REFERENCES dbo.MISJE(MISJA_ID_PK),

  CONSTRAINT CK_MISJE_STATUSY_PODSEGMENT
    CHECK (
      (SEGMENT = N'CEL' AND PODSEGMENT IS NOT NULL)
      OR
      (SEGMENT <> N'CEL' AND PODSEGMENT IS NULL)
    )
)
GO

CREATE INDEX IX_MISJE_STATUSY
ON dbo.MISJE_STATUSY (MISJA_ID_FK, DATA_STATUS DESC)
GO
