USE WoW_PL
GO

CREATE TABLE dbo.NPC (
  NPC_ID_PK BIGINT IDENTITY(1, 1) NOT NULL,
  NAZWA_EN NVARCHAR(55) NOT NULL,
  DATA_DODANIA DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

  CONSTRAINT PK_NPC PRIMARY KEY (NPC_ID_PK),
  CONSTRAINT UX_NPC_NAZWA_EN UNIQUE (NAZWA_EN)
)
GO