from scraper_wowhead import *

# NAJPIERW PRZYGOTOWAC EXCEL W FOLDERZE 'SUROWE' --> 'wowhead_id_kraina_dodatek'
#    A. WEJSC W LINK W PIERWSZEJ ZAKLADCE
#    B. SKOPIOWAC RECZNIE 3 KOLUMNY (JEST PRZYCISK NA TO NA STRONIE)
#    B. ODSWIEZYC TABELE W DRUGIM ARKUSZU
# NASTEPNIE ODPALIC PONIZSZY SKRYPT.
# DANE SA 'DOPISYWANE' W BATCHACH=10 POD OSTATNIM WIERSZEM I SKRYPT SPRAWDZA, CZY DANY LINK JUZ WYSTEPUJE (JAK TAK TO PRZECHODZI DALEJ)
buduj_mapping_01()