from scraper_wowhead import *
from pomocnicze_funkcje_sql import *
import pandas as pd

silnik = utworz_engine_do_db()

sciezka = r"D:\MyProjects_4Fun\projects\World of Warcraft\excel-mappingi\mapping_01.xlsx"
arkusz = "mapping_01"
kolumny = ["MISJA_ID_Z_GRY", "MISJA_TYTUL_EN", "DODATEK_EN", "MISJA_URL_WOWHEAD", 
           "NAZWA_LINII_FABULARNEJ_EN", "DODANO_W_PATCHU", "KONTYNENT_EN",
           "KONTYNENT_PL", "KRAINA_EN_FINAL", "KRAINA_PL", "DODATEK_PL"]
df = pd.read_excel(sciezka, sheet_name=arkusz, usecols=kolumny).dropna(how="all")
df["NAZWA_LINII_FABULARNEJ_EN"] = df["NAZWA_LINII_FABULARNEJ_EN"].fillna("NoData")


# NAJPIERW PRZYGOTOWAC EXCEL W FOLDERZE 'SUROWE' --> 'wowhead_id_kraina_dodatek'
#    A. WEJSC W LINKI W PIERWSZEJ ZAKLADCE
#    B. SKOPIOWAC RECZNIE 3 KOLUMNY (JEST PRZYCISK NA TO NA STRONIE) DO POSZCZEGOLNCH TABEL
#    B. ODSWIEZYC TABELE W DRUGIM ARKUSZU (TAM JUZ DANE SA ZAGREGOWANE Z KILKU LINKOW)
# NASTEPNIE ODPALIC PONIZSZY SKRYPT.
# DANE SA 'DOPISYWANE' W BATCHACH=10 POD OSTATNIM WIERSZEM I SKRYPT SPRAWDZA, CZY DANY LINK JUZ WYSTEPUJE (JAK TAK TO PRZECHODZI DALEJ)
buduj_mapping_01()


# TUTAJ JEST ROBIONY UPDATE TABELI dbo.MISJE O POZOSTALE ATRYBUTY JAK LINK DO WOWHEAD, GLOWNE ID MISJI Z GRY ITP.
# ZANIM ODPALE SKRYPT, TRZEBA SPRAWDZIC CZY FORMULY W EXCELU NIE WYSYPALY SIE PO DODANIU DANYCH WYZEJ
# aktualizuj_misje_z_excela(
#     df, 
#     silnik
#     )