CREATE TRIGGER trg_MISJE_DATAUPDATE
ON dbo.MISJE
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE m
    SET DATA_UPDATE = SYSDATETIME()
    FROM dbo.MISJE AS m
    INNER JOIN inserted AS i
        ON m.MISJA_ID_MOJE_PK = i.MISJA_ID_MOJE_PK;
END