SELECT
    v.NPC_ID AS ID,
    n.NAZWA, n.RASA,
    COUNT(ms.TRESC) AS ile_wypowiedzi
FROM dbo.MISJE_STATUSY AS ms
INNER JOIN dbo.MISJE AS m
    ON ms.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
CROSS APPLY (
    VALUES
        (m.NPC_START_ID),
        (m.NPC_KONIEC_ID)
) AS v(NPC_ID)
INNER JOIN dbo.NPC AS n
    ON v.NPC_ID = n.NPC_ID_MOJE_PK
WHERE ms.STATUS = N'0_ORYGINAŁ'
  AND v.NPC_ID IS NOT NULL
GROUP BY v.NPC_ID, n.NAZWA, n.RASA
HAVING COUNT(ms.TRESC) >= 25
ORDER BY ile_wypowiedzi DESC;