DROP TABLE IF EXISTS #MISJE_IDKI;
DROP TABLE IF EXISTS #ARCHIWUM;

WITH MISJE_IDKI AS (
    SELECT DISTINCT MISJA_ID_Z_GRY
    FROM dbo.ARCHIWUM_MISJE_DIALOGI
),

ARCHWIUM AS (
    SELECT
        A.MISJA_ID_Z_GRY, S.SEGMENT,
        SUM(LEN(A.TRESC)) AS ZNAKI_ARCH,
        COUNT(A.TRESC) AS ZDANIA_ARCH
    FROM dbo.ARCHIWUM_MISJE_DIALOGI AS A
    INNER JOIN dbo.MISJE AS M
      ON A.MISJA_ID_Z_GRY = M.MISJA_ID_Z_GRY
    CROSS APPLY (
        SELECT
            CASE
                WHEN A.SEGMENT = 'CEL' AND A.PODSEGMENT = 'GŁÓWNY_CEL'    THEN 'GŁÓWNY_CEL'
                WHEN A.SEGMENT = 'CEL' AND A.PODSEGMENT = 'PODRZĘDNY_CEL' THEN 'PODRZĘDNY_CEL'
                ELSE A.SEGMENT
            END AS SEGMENT
    ) AS S
    WHERE 1=1
      AND M.STATUS_MISJI <> -1
      AND A.MISJA_ID_Z_GRY IN /*(SELECT MISJA_ID_Z_GRY FROM MISJE_IDKI)*/ (86521)
      AND A.STATUS = N'0_ORYGINAŁ'
    GROUP BY 
        A.MISJA_ID_Z_GRY, S.SEGMENT
),

TERAZ_MISJE AS (
    SELECT 
        M.MISJA_ID_Z_GRY, S.SEGMENT,
        SUM(LEN(MS.TRESC)) AS ZNAKI_TERAZ,
        COUNT(MS.TRESC) AS ZDANIA_TERAZ
    FROM dbo.MISJE_STATUSY AS MS
    INNER JOIN dbo.MISJE AS M
      ON MS.MISJA_ID_MOJE_FK = M.MISJA_ID_MOJE_PK
    CROSS APPLY (
        SELECT
            CASE
                WHEN MS.SEGMENT = 'CEL' AND MS.PODSEGMENT = 'GŁÓWNY_CEL'    THEN 'GŁÓWNY_CEL'
                WHEN MS.SEGMENT = 'CEL' AND MS.PODSEGMENT = 'PODRZĘDNY_CEL' THEN 'PODRZĘDNY_CEL'
                ELSE MS.SEGMENT
            END AS SEGMENT
    ) AS S
    WHERE 1=1
      AND M.STATUS_MISJI <> -1
      AND M.MISJA_ID_Z_GRY IN /*(SELECT MISJA_ID_Z_GRY FROM MISJE_IDKI)*/ (86521)
      AND MS.STATUS = N'0_ORYGINAŁ'
    GROUP BY
        M.MISJA_ID_Z_GRY, S.SEGMENT
),

TERAZ_DIALOGI AS (
    SELECT 
        M.MISJA_ID_Z_GRY,  DS.SEGMENT,
        SUM(LEN(DS.TRESC)) AS ZNAKI_TERAZ,
        COUNT(DS.TRESC) AS ZDANIA_TERAZ
    FROM dbo.DIALOGI_STATUSY AS DS
    INNER JOIN dbo.MISJE AS M
      ON DS.MISJA_ID_MOJE_FK = M.MISJA_ID_MOJE_PK
    WHERE 1=1
      AND M.MISJA_ID_Z_GRY IN /*(SELECT MISJA_ID_Z_GRY FROM MISJE_IDKI)*/ (86521)
      AND DS.STATUS = N'0_ORYGINAŁ'
    GROUP BY
        M.MISJA_ID_Z_GRY,  DS.SEGMENT
),

TERAZ AS (
    SELECT *
    FROM TERAZ_MISJE

    UNION ALL

    SELECT *
    FROM TERAZ_DIALOGI
)

-- ================= DODAC DIALOGI =================
SELECT 
    M.MISJA_ID_Z_GRY, S1.SEGMENT,
    SUM(LEN(MS.TRESC)) AS ZNAKI_WSPOLNE,
    COUNT(MS.TRESC) AS ZDANIA_WSPOLNE
FROM dbo.MISJE_STATUSY AS MS
CROSS APPLY (
    SELECT
        CASE
            WHEN MS.SEGMENT = 'CEL' AND MS.PODSEGMENT = 'GŁÓWNY_CEL'    THEN 'GŁÓWNY_CEL'
            WHEN MS.SEGMENT = 'CEL' AND MS.PODSEGMENT = 'PODRZĘDNY_CEL' THEN 'PODRZĘDNY_CEL'
            ELSE MS.SEGMENT
        END AS SEGMENT
) AS S1
INNER JOIN dbo.MISJE AS M
  ON MS.MISJA_ID_MOJE_FK = M.MISJA_ID_MOJE_PK
 AND M.MISJA_ID_Z_GRY IN (86521)
INNER JOIN dbo.ARCHIWUM_MISJE_DIALOGI AS AMD
  ON MS.TRESC = AMD.TRESC
 AND S1.SEGMENT = CASE WHEN AMD.SEGMENT = 'CEL' AND AMD.PODSEGMENT = 'GŁÓWNY_CEL' THEN 'GŁÓWNY_CEL'
                       WHEN AMD.SEGMENT = 'CEL' AND AMD.PODSEGMENT = 'PODRZĘDNY_CEL' THEN 'PODRZĘDNY_CEL'
                       ELSE AMD.SEGMENT
                  END -- nie moge CROSS APPLY, bo zapytanie nie widzialoby jeszcze tej tabeli
 AND AMD.MISJA_ID_Z_GRY IN (86521)
 AND AMD.TABELA = 'MISJE_STATUSY'
 AND AMD.STATUS = N'0_ORYGINAŁ'
WHERE 1=1
  AND MS.STATUS = N'0_ORYGINAŁ'
GROUP BY
    M.MISJA_ID_Z_GRY, S1.SEGMENT

--SELECT 
--    T.MISJA_ID_Z_GRY, T.SEGMENT,
--    T.ZNAKI_TERAZ, A.ZNAKI_ARCH,
--    T.ZDANIA_TERAZ, A.ZDANIA_ARCH
--FROM TERAZ AS T
--INNER JOIN ARCHWIUM AS A
--  ON T.MISJA_ID_Z_GRY = A.MISJA_ID_Z_GRY
-- AND T.SEGMENT = A.SEGMENT