SELECT 
	'MISJE_STATUSY' AS TABELA, 
	m.MISJA_ID_Z_GRY, ms.SEGMENT, ms.PODSEGMENT, ms.STATUS,
	ms.NR, NULL AS NR_WYPOWIEDZI, m.NPC_START_ID AS NPC_ID_FK,
	ms.TRESC
FROM dbo.MISJE_STATUSY AS ms
INNER JOIN dbo.MISJE AS m
  ON ms.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  AND m.MISJA_ID_MOJE_PK = 5460

UNION ALL

SELECT 
	'DIALOGI_STATUSY' AS TABELA, 
	m.MISJA_ID_Z_GRY, ds.SEGMENT, NULL AS PODSEGMENT, ds.STATUS,
	ds.NR_BLOKU_DIALOGU AS NR, ds.NR_WYPOWIEDZI, ds.NPC_ID_FK, ds.TRESC
FROM dbo.DIALOGI_STATUSY AS ds
INNER JOIN dbo.MISJE AS m
  ON ds.MISJA_ID_MOJE_FK = m.MISJA_ID_MOJE_PK
WHERE 1=1
  AND m.MISJA_ID_MOJE_PK = 5460