WITH UNIKALNE_DATY AS (
    SELECT DISTINCT
        DATA_STATUS
    FROM dbo.MISJE_ZMIANY_WIKI
),

RANKING_DAT AS (
    SELECT
        DATA_STATUS,
        ROW_NUMBER() OVER (ORDER BY DATA_STATUS DESC) AS RNK
    FROM UNIKALNE_DATY
),

DO_WYRZUCENIA AS (
    SELECT
        DATA_STATUS
    FROM RANKING_DAT
    WHERE RNK >= 3
)

DELETE FROM dbo.MISJE_ZMIANY_WIKI
WHERE DATA_STATUS IN (
    SELECT DATA_STATUS
    FROM DO_WYRZUCENIA
);

WITH UNIKALNE_DATY AS (
    SELECT DISTINCT
        DATA_STATUS
    FROM dbo.MISJE_ZMIANY_WIKI
),

RANKING_DAT AS (
    SELECT
        DATA_STATUS,
        ROW_NUMBER() OVER (ORDER BY DATA_STATUS DESC) AS RNK
    FROM UNIKALNE_DATY
),

DANE AS (
    SELECT
        MZW.ZAKRES,
        MZW.LICZBA_MISJI,
        MZW.DATA_STATUS,
        RD.RNK
    FROM dbo.MISJE_ZMIANY_WIKI AS MZW
    INNER JOIN RANKING_DAT AS RD
        ON MZW.DATA_STATUS = RD.DATA_STATUS
    WHERE RD.RNK IN (1, 2)
),

WYNIK AS (
    SELECT
        ZAKRES,
        MAX(CASE WHEN RNK = 2 THEN DATA_STATUS END) AS DATA_POPRZEDNIA,
        MAX(CASE WHEN RNK = 1 THEN DATA_STATUS END) AS DATA_NAJNOWSZA,
        MAX(CASE WHEN RNK = 2 THEN LICZBA_MISJI END) AS LICZBA_MISJI_POPRZEDNIA,
        MAX(CASE WHEN RNK = 1 THEN LICZBA_MISJI END) AS LICZBA_MISJI_NAJNOWSZA,
        MAX(CASE WHEN RNK = 1 THEN LICZBA_MISJI END)
            - MAX(CASE WHEN RNK = 2 THEN LICZBA_MISJI END) AS ROZNICA
    FROM DANE
    GROUP BY ZAKRES
)

SELECT *
FROM WYNIK
WHERE ROZNICA <> 0
;
