DROP TABLE IF EXISTS #misje_z_redakcja;

WITH statusy_liczby AS (
    SELECT
        MISJA_ID_MOJE_FK,
        CAST(SUBSTRING(STATUS, 1, CHARINDEX('_', STATUS) - 1) AS INT) AS status_liczba
    FROM dbo.MISJE_STATUSY
    GROUP BY MISJA_ID_MOJE_FK, STATUS
)
--SELECT MISJA_ID_MOJE_FK
--INTO #misje_z_redakcja
--FROM statusy_liczby
--GROUP BY MISJA_ID_MOJE_FK
--HAVING SUM(status_liczba) = 6
--;

--UPDATE dbo.MISJE
--SET STATUS_MISJI = 0
--WHERE STATUS_MISJI IS NULL
--;

UPDATE dbo.MISJE
SET STATUS_MISJI = -1
WHERE MISJA_ID_Z_GRY = 123456789
;