USE WoW_PL
;

CREATE TABLE dbo.MISJE_ZMIANY_WIKI (
  TECH_ID BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
  ZAKRES VARCHAR(20)            NOT NULL,
  LICZBA_MISJI INT              NOT NULL,
  DATA_STATUS DATETIME2         NOT NULL
)
;