USE WoW_PL
;

CREATE TABLE dbo.MISJE_WSKAZNIKI_ZGODNOSCI (
    TECH_ID BIGINT IDENTITY(1, 1) NOT NULL,

    MISJA_ID_MOJE_FK BIGINT NOT NULL,

    SEGMENT NVARCHAR(30) NOT NULL
        CHECK (
            SEGMENT IN (
                N'TYTUŁ',N'GŁÓWNY_CEL',N'PODRZĘDNY_CEL',N'TREŚĆ',N'POSTĘP',
                N'ZAKOŃCZENIE',N'NAGRODY',N'DYMEK',N'GOSSIP'
            )
        ),

    WSKAZNIK_ZGODNOSCI DECIMAL(10, 4) NOT NULL,
    PROC_WSPOLNYCH_ZNAKOW DECIMAL(10, 4) NOT NULL,
    PROC_WSPOLNYCH_ZDAN DECIMAL(10, 4) NOT NULL,

    ZNAKI_TERAZ BIGINT NOT NULL,
    ZNAKI_ARCH BIGINT NOT NULL,
    ZNAKI_WSPOLNE BIGINT NOT NULL,

    ZDANIA_TERAZ BIGINT NOT NULL,
    ZDANIA_ARCH BIGINT NOT NULL,
    ZDANIA_WSPOLNE BIGINT NOT NULL,

    KIERUNEK_ZMIANY_ZNAKI NVARCHAR(20) NOT NULL
        CHECK (
            KIERUNEK_ZMIANY_ZNAKI IN (
                N'TYLE SAMO',
                N'WIECEJ TERAZ',
                N'MNIEJ TERAZ'
            )
        ),

    KIERUNEK_ZMIANY_LICZBY_ZDAN NVARCHAR(20) NOT NULL
        CHECK (
            KIERUNEK_ZMIANY_LICZBY_ZDAN IN (
                N'TYLE SAMO',
                N'WIECEJ TERAZ',
                N'MNIEJ TERAZ'
            )
        ),

    DATA_DODANIA DATETIME2(0) NOT NULL
        CONSTRAINT DF_MISJE_WSKAZNIKI_ZGODNOSCI_DATA_DODANIA
        DEFAULT SYSDATETIME(),

    CONSTRAINT PK_MISJE_WSKAZNIKI_ZGODNOSCI
        PRIMARY KEY CLUSTERED (TECH_ID),

    CONSTRAINT FK_MISJE_WSKAZNIKI_ZGODNOSCI_MISJE
        FOREIGN KEY (MISJA_ID_MOJE_FK)
        REFERENCES dbo.MISJE (MISJA_ID_MOJE_PK),

    CONSTRAINT UQ_MISJE_WSKAZNIKI_ZGODNOSCI_MISJA_SEGMENT
        UNIQUE (MISJA_ID_MOJE_FK, SEGMENT)
)
;

CREATE INDEX IX_MISJE_WSKAZNIKI_ZGODNOSCI_MISJA
ON dbo.MISJE_WSKAZNIKI_ZGODNOSCI (MISJA_ID_MOJE_FK)
;