USE WoW_PL
;

CREATE TABLE dbo.MISJE_STATUSY (
  TECH_ID BIGINT IDENTITY(1, 1)      NOT NULL,
  MISJA_ID_MOJE_FK BIGINT            NOT NULL,

  SEGMENT NVARCHAR(30)               NOT NULL
    CHECK (SEGMENT IN (N'TYTU£', N'CEL', N'TREŒÆ', N'POSTÊP', N'ZAKOÑCZENIE', N'NAGRODY')),

  PODSEGMENT NVARCHAR(30)                NULL
    CHECK (PODSEGMENT IN (N'G£ÓWNY_CEL', N'PODRZÊDNY_CEL')),

  STATUS NVARCHAR(30)                NOT NULL
    CHECK (STATUS IN (N'0_ORYGINA£', N'1_PRZET£UMACZONO', N'2_ZREDAGOWANO', N'3_ZATWIERDZONO')),

  NR INT                             NOT NULL,

  TRESC NVARCHAR(MAX)                    NULL,
  DATA_STATUS DATETIME2              NOT NULL DEFAULT SYSDATETIME(),

  HASH_EN CHAR(16)                       NULL,

  CONSTRAINT PK_MISJE_STATUSY PRIMARY KEY (TECH_ID),

  CONSTRAINT FK_MISJE_STATUSY_MISJE
    FOREIGN KEY (MISJA_ID_MOJE_FK) REFERENCES dbo.MISJE(MISJA_ID_MOJE_PK),

  CONSTRAINT CK_MISJE_STATUSY_PODSEGMENT
    CHECK (
      (SEGMENT = N'CEL' AND PODSEGMENT IS NOT NULL)
      OR
      (SEGMENT <> N'CEL' AND PODSEGMENT IS NULL)
    )
)
;


CREATE INDEX IX_MISJE_STATUSY
ON dbo.MISJE_STATUSY (MISJA_ID_MOJE_FK, SEGMENT, PODSEGMENT, NR, DATA_STATUS DESC)
;

CREATE UNIQUE INDEX UX_MISJE_STATUSY_ORYGINAL
ON dbo.MISJE_STATUSY (MISJA_ID_MOJE_FK, SEGMENT, PODSEGMENT, NR)
WHERE STATUS = N'0_ORYGINA£'
;